### ISSUE TITLE
Comment lines per class

### ISSUE THREAD

**Issue by vkdaros** [analizo/analizo#10]
Count the total of comment lines in each class.

**Comment by joenio** [comment]
proposed solution:
* add new Analizo extractor for [CLOC][] and implement new module metric to output the number of comments on source code.
* keep the Analizo sloccount extractor

[CLOC]:https://github.com/AlDanial/cloc

**Comment by joenio** [comment]
we are going to keep in analizo only the metrics calculated by analizo itself, and proposing to users to use specific tools to obtain specific metrics, for the case of metrics provided by CLOC we suggests the users to use the CLOC and get the metrics CLOC provide.

we already removed sloccount from analizo side for example, in this way that issue has no sense anymore, closing issue.
