### ISSUE TITLE
YAML Error

### ISSUE THREAD

**Issue by rafamanzo** [analizo/analizo#106]
Hi, it has been a long time :)

Running analizo 1.20.0~rc1 on Debian Stretch with the following repository (https://github.com/rafamanzo/runge-kutta-vtk) yields the following error:

```bash
root@a6e07d08c97b:/runge-kutta-vtk# analizo metrics .
YAML Error: Invalid element in map
   Code: YAML_LOAD_ERR_BAD_MAP_ELEMENT
   Line: 14523
   Document: 1
 at /usr/share/perl5/YAML/Loader.pm line 350.
```

Do you have any insight on the cause? I can help on getting this fixed :)

Thanks in advance!

**Comment by paulormm** [comment]
We can mitigate this problem by making a downgrade to version "1.19.1" (using Debian Jessie). I think @joenio will fix it to release the Analizo 1.20.0. Do you have any comment @joenio ?

**Comment by joenio** [comment]
now, we have the warning related on issue #99, but the error related here this issue was fixed.

**Comment by rafamanzo** [comment]
Thank you!
