### ISSUE TITLE
when is experimental

### ISSUE THREAD

**Issue by eserte** [analizo/analizo#109]
While running the test suite the following warnings are visible with newer perls (probably with perl >= 5.18):
```
when is experimental at /home/cpansand/.cpan/build/2018010621/Analizo-1.20.2-0/t/features/step_definitions/analizo_steps.pl line 110.
when is experimental at /home/cpansand/.cpan/build/2018010621/Analizo-1.20.2-0/t/features/step_definitions/analizo_steps.pl line 113.
```
The future of `when` and smartmatch is unclear and in perl 5.27.7 it was even removed (but maybe will re-added in 5.27.8) again. Nowadays it's probably better to use just class if/elsif/else instead.

**Comment by joenio** [comment]
fixed 510ef740de1ca0dd6ef482b1db2feb9374c76a63
