### ISSUE TITLE
Add support to analyze Python code

### ISSUE THREAD

**Issue by gerardorosiles** [analizo/analizo#118]
It is cited in a couple of places that adding support to other languages is straightforward. It would be goof to also have a guiding document to implement this fast and then contribute the code by persons interested on supporting another language like Python.

**Comment by joenio** [comment]
hi @gerardorosiles we have tried add python support as you can see on branch below:

https://github.com/analizo-mes/analizo/tree/issue_04_pythonSupport

but with no success, if you can try I can explain, maybe you can contribute writing a document step-by-step how to add new languages, unfortunately I have no time to write these tutorial for now.
