### ISSUE TITLE
analizo aborting for all commands

### ISSUE THREAD

**Issue by gerardorosiles** [analizo/analizo#119]
Analizo version 1.20.7
Doxyparse version 1.8.14-4

Tested with the following packages:

https://github.com/mlpack/mlpack.git
https://github.com/mdabros/SharpLearning.git
https://github.com/imageprocessor/cv4j.git

Getting the following errors for all commands:
Can't locate Env/Path.pm in @INC (you may need to install the Env::Path module) (@INC contains: /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.24.1 /usr/local/share/perl/5.24.1 /usr/lib/x86_64-linux-gnu/perl5/5.24 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.24 /usr/share/perl/5.24 /usr/local/lib/site_perl /usr/lib/x86_64-linux-gnu/perl-base) at /usr/share/perl5/Analizo/Command.pm line 6.
BEGIN failed--compilation aborted at /usr/share/perl5/Analizo/Command.pm line 6.
Compilation failed in require at /usr/share/perl5/Analizo.pm line 2.
BEGIN failed--compilation aborted at /usr/share/perl5/Analizo.pm line 2.
Compilation failed in require at /usr/bin/analizo line 3.
BEGIN failed--compilation aborted at /usr/bin/analizo line 3.

**Comment by joenio** [comment]
@gerardorosiles this a bug on last analizo release, you can solve this installing the CPAN module Env::Path, on Debian systems you can run: `apt install libenv-path-perl`

see #115

**Comment by joenio** [comment]
@gerardorosiles try the latest 1.20.8 version, follow steps below on a Debian 9 Stretch:

* http://www.analizo.org/installation.html

**Comment by joenio** [comment]
just for record: doxyparse fails analyzing mlpack source-code, bug reported #120.
