### ISSUE TITLE
analyze code from classes that use generics with wildcards

### ISSUE THREAD

**Issue by joenio** [analizo/analizo#121]
copied from #63 

When analyzing Kalibro https://github.com/mezuro/kalibro we have noted some things:

* Analizo does not analyze code from classes that use generics with wildcards (<?>). However, if there's one wildcard and another not that specific (< T extends Comparable<? super T> >), Analizo analyzes that class.

**Comment by lucasca73** [comment]
@joenio i am running Analizo on this class, just to check the issue... and i dont see any problems on the log produced, the analysis produced by Analizo seems correct. 

```Java
public class GenericClass<T> {

    public void print(){
        System.out.print(T.class);
    }
}

public class Wildcard_sample {

    public void helloWildcard(){
        GenericClass<?> variable = new GenericClass<String>();
        variable.print();
    }

}
```

**Comment by joenio** [comment]
@lucasca73 thanks. I suppose this bug is in some old doxyparse version.

Maybe can you implement a testcase to ensure that analizo continues working properly. To implement this test, first you will need add some sample code on t/samples/.

**Comment by joenio** [comment]
Java doc about generic wildcards:
* https://docs.oracle.com/javase/tutorial/extra/generics/wildcards.html

Bugs already fixed on doxygen upstream about wildcards (not confirmed if it is in fact related to this issue):
* https://bugzilla.gnome.org/show_bug.cgi?id=631675
* https://bugzilla.gnome.org/show_bug.cgi?id=583958
