### ISSUE TITLE
equal module names to files that are not in the same folder

### ISSUE THREAD

**Issue by joenio** [analizo/analizo#123]
copied from #63 

When analyzing Kalibro https://github.com/mezuro/kalibro we have noted some things:

* Analizo sets equal module names to files that are not in the same folder. For example, all implementation classes and test classes will have the same module name.

**Comment by Rdlenke** [comment]
I wasn't able to understand this problem very well. When I tested it, the module names of implementation classes and test classes were different.

```
_filename:
  - KalibroCore/src/org/kalibro/AbstractMetricResult.java
_module: org::kalibro::AbstractMetricResult
acc: 13
accm: 1
amloc: 3.33333333333333
anpm: 0.666666666666667
cbo: 0
dit: 2
lcom4: 3
loc: 10
mmloc: 4
noa: 2
noc: 2
nom: 3
npa: 0
npm: 2
rfc: 3
sc: 0
---
_filename:
  - KalibroTests/unit/org/kalibro/AbstractMetricResultTest.java
_module: org::kalibro::AbstractMetricResultTest
acc: 0
accm: 1
amloc: 4
anpm: 0.5
cbo: 2
dit: 4
lcom4: 2
loc: 24
mmloc: 6
noa: 1
noc: 0
nom: 6
npa: 0
npm: 4
rfc: 16
sc: 4
---
```

Complete output [here][output].

[output]:https://gist.github.com/Rdlenke/d54706f5aa8c4871962cdcd082e424b0

**Comment by joenio** [comment]
@Rdlenke thanks. I also couldn't found any case in the Kalibro source-code that confirm this issue.

Closing the issue.
