### ISSUE TITLE
missing module on analizo metrics tool output

### ISSUE THREAD

**Issue by joenio** [analizo/analizo#124]
copied from #63 

When analyzing Kalibro https://github.com/mezuro/kalibro we have noted some things:

* The class https://github.com/mezuro/kalibro/blob/master/KalibroCore/src/org/kalibro/AbstractModuleResult.java is not analyzed. I could not understand why.

**Comment by Rdlenke** [comment]
The https://github.com/mezuro/kalibro/blob/master/KalibroCore/src/org/kalibro/AbstractModuleResult.java file was analized when I used ```analizo metrics``` in the Kalibro folder.

```java
_filename:
  - KalibroCore/src/org/kalibro/AbstractMetricResult.java
_module: org::kalibro::AbstractMetricResult
acc: 13
accm: 1
amloc: 3.33333333333333
anpm: 0.666666666666667
cbo: 0
dit: 2
lcom4: 3
loc: 10
mmloc: 4
noa: 2
noc: 2
nom: 3
npa: 0
npm: 2
rfc: 3
sc: 0
```

**Comment by joenio** [comment]
Despite the issue refers to AbstractModuleResult.java and the output of `analizo metrics` refers to AbstractMetricResult.java I beleave that the problem was solved, I ran `analizo metrics` here and confirmed that analizo reports AbstractModuleResult.java properly, as you already verified before.

Thank you very much! Closing this issue.
