### ISSUE TITLE
Doxyparse does not print protection of non-public functions

### ISSUE THREAD

**Issue by mateus-andrade** [analizo/analizo#136]
In following lines: https://github.com/analizo/doxyparse/blob/master/addon/doxyparse/doxyparse.cpp#L235 and https://github.com/analizo/doxyparse/blob/master/addon/doxyparse/doxyparse.cpp#L269, it is possible to note that Doxyparse just print the protection when it is public, ignoring when the protection is private or protected, I don't have sure but I think that it could cause inconsistencies in analizo metrics.

**Comment by joenio** [comment]
Currently the Analizo just uses this to calculates the number of public attributes and methods, then doesn't causes any inconsistency on metrics, for sure would be better if Doxyparse could identifies the non-public protection as well, this way we could in near future add metrics on Analizo about protected and private attributes and methods. But for now it is not a priority.

**Comment by joenio** [comment]
added on doxyparse the information about protection
