### ISSUE TITLE
I could not collect metrics for a project

### ISSUE THREAD

**Issue by motta-tiago** [analizo/analizo#137]
Hello developers,

I installed Analizo package to get metrics about a set of open sources projects, but I had any problems during its uses.

The first problem occurred when I try to get the metrics of kdelibs project. I indicated as input the clone of the repository, but Analizo reports an execution error. 

I tried to collect history metrics of the same project, but I had problems also.

I tried to use a project with fewer commits (Minuet project), but I was not successful either.

What should I do to correct these errors?

The clone of kdelibs project is available in: https://github.com/KDE/kdelibs.git

The clone of minuet project is available in: https://github.com/KDE/minuet.git

I attached bellow the error messages. Completing the information: I use Linux Debian testing (4.16.5-1 x86_64) as an operating system. The version of Analizo I used was 1.21.0. The version used for Doxyparse was 1.8.14.

1. Scenario:
**Command:** 
analizo metrics kdelibs

**Result:**
YAML::XS::Load Error: The problem:

    found unknown escape character

was found at document: 1, line: 602661, column: 27
while parsing a quoted scalar at line: 602661, column: 9

2. Scenario:
**Command:** 
analizo metrics-history kdelibs

**Result:**
YAML::XS::Load Error: The problem:

    did not find expected <document start>

was found at document: 89, line: 462, column: 1

3. Scenario:

**Command:**
 analizo metrics-history minuet

**Result:**
YAML::XS::Load Error: The problem:

    did not find expected <document start>

was found at document: 21, line: 116, column: 1

**Comment by joenio** [comment]
thanks @motta-tiago for the details about this Analizo issue.

I split this issue on two minor issues (#138 #139) and schedule to the version 1.23.0 planned to be released at June end.

You can see the roadmap on milestones at:

* https://github.com/analizo/analizo/milestones

**Comment by joenio** [comment]
hi @motta-tiago can you check if the latest commits on analizo and doxyparse source code fixes these issues?
