### ISSUE TITLE
graphml --modules generating unwanted elements

### ISSUE THREAD

**Issue by gerardorosiles** [analizo/analizo#146]
We have been doing tests in our app with the following source code package:
[https://github.com/imageprocessor/cv4j]

We are using analizo graph --modules to analyze dependencies. We are seeing the following unexpected analizo behaviors in the  DOT file.

1. Analizo includes dependencies (i.e., graph nodes) to external Java dependencies. For instance on cv4j we get:
java.io.Serializable
java.util.concurrent.ThreadFactory
RecycleView
Comparable
RuntimeException

2. Analizo is including enumerations and inner Java classes as nodes. According to help info the --modules option should:

"Group the functions by modules(files), and only represent calls between modules"

We are getting the following graph node elements (and edges):

a) com::cv4j::app::adapter::GridViewFilterAdapter::ViewHolder 
where there is a file GridViewFilterAdapter.java that in addition to class GridViewFilterAdapter, there is an inner helper class called: ViewHolder

b) com::cv4j::app::adapter::SpitalConvAdapter::ViewHolder
where there is a file SpitalViewFilterAdapter.java that in addition to class SpitalViewFilterAdapter, there is an inner helper class called: ViewHolder

c) com::cv4j::app::menu::MenuManager::MenuType
where there is a file MenuManager.java  where the  MenuManager defines a public enumeration MenuType.  

We believe these inner classes and enumeration should not be part of the graph when the --modules option is used. In particular, the naming convention for the nodes:
                              com.acme.pack1.class1
                              com.acme.pack2.class2
establishes that the string after the last period is the class name and rest of the string is the package name. So with inner classess or enumerations we have:
                               com.acme.pack1.class1.innerClass1
                               com.acme.pack1.class1.enum1
there is no way to know that the last component of the string is not a class. So if this naming convention is used to process Analizo's output, then  the processing application will think that there is a package called: com.acme.pack1.class1 and two files innerClass1.java and enum1.java containing the respective classes.

These issues could be captured with a post-processing step, but it seems is is a bug on the Analizo side.

Thanks,

Gerardo

**Comment by joenio** [comment]
moving discussions to issues #151 #152
