### ISSUE TITLE
Error analyzing metrics of file 

### ISSUE THREAD

**Issue by alonzanbar** [analizo/analizo#147]
Getting :
YAML::XS::Load Error: The problem:

    found unknown escape character

was found at document: 1, line: 128, column: 42

while parsing a quoted scalar at line: 128, column: 9

attached is the  file causing  the error
 [bad-file.tar.gz](https://github.com/analizo/analizo/files/2373898/bad-file.tar.gz)

**Comment by joenio** [comment]
hi @alonzanbar 

Can you try the latest Analizo 1.22.0 release? Upgrade the doxyparse to the latest version 1.8.14-7 too.

**Comment by alonzanbar** [comment]
Thanks a lot Ill try and update

בתאריך 26 בספט' 2018 18:16,‏ "Joenio Costa" <notifications@github.com> כתב:

hi @alonzanbar <https://github.com/alonzanbar>

Can you try the latest Analizo 1.22.0 release? Upgrade the doxyparse to the
latest version 1.8.14-7 too.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/analizo/analizo/issues/147#issuecomment-424753345>, or mute
the thread

**Comment by alonzanbar** [comment]
Hi , 
Now I cannot analyze at all 
getting :
Can't locate object method "calculate" via package "Analizo::GlobalMetric::TotalEloc" at /usr/local/share/perl/5.22.1/Analizo/GlobalMetrics.pm line 114.

**Comment by alonzanbar** [comment]
Ok , 
I found the bug. it was a cache issue ( those are the trickiest...):
The cache wasn't refreshing after upgrading and the old "Eloc" calculator was registered at the old version :
```
# calculate metrics
  my $metrics_cache_key = "metrics://$tree_id";
  my $metrics = $self->cache->get($metrics_cache_key);
  if (!defined $metrics) {
    $metrics = Analizo::Metrics->new(model => $self->model);
    $metrics->data();
    $self->cache->set($metrics_cache_key, $metrics);
  }
  $self->metrics($metrics);

  $self->cleanup();
}
```

**Comment by joenio** [comment]
nice, thanks for the feedback! I'm going to implement the cache by the analizo version
