### ISSUE TITLE
Installation issue while installing from Debian package

### ISSUE THREAD

**Issue by mahintalukder** [analizo/analizo#149]
Hi I have been trying to install analizo for my ubuntu 16.4 OS. I have followed the instruction from the following  link https://github.com/analizo/analizo/blob/master/INSTALL.md
However during the installation process I have found the following error. 

The following packages have unmet dependencies.
 analizo : Depends: libzmq-ffi-perl but it is not installable
E: Unable to correct problems, you have held broken packages.

I have tried to install the missing perl module but no luck. Can anyone  please suggest me something to overcome this issue. Alternatively are there any other procedure that i can follow to install analizo on my machine. I am trying to find complexity metrics and dependency graph using analizo.

**Comment by joenio** [comment]
hello @mahintalukder

the analizo debian packages is ok on debian systems only, sorry.

you can try install via CPAN on ubuntu or switch to a Debian system (I suggest Buster release).

to install via cpan just run `cpan i Analizo` or `cpanm Analizo` or any other cpan client.

before running cpan install the dependencies listed on doc below:
* https://github.com/analizo/analizo/blob/master/HACKING.md#installing-dependencies-on-non-debian-systems

**Comment by mahintalukder** [comment]
Hi @joenio 
Thank you so much for the instruction. I have successfully installed Analizo on my ubuntu machine. The process was quite simple but i had to install quite a lot modules separately. at the final stage i was having difficulties with following message.

root@mahin:~# cpanm Analizo
--> Working on Analizo
....
Fetching http://www.cpan.org/authors/id/J/JO/JOENIO/Analizo-1.22.0.tar.gz ... OK
Configuring Analizo-1.22.0 ... OK
Building and testing Analizo-1.22.0 ... FAIL
! Timed out (> 1800s). Use --verbose to retry.
! Installing Analizo failed. See /root/.cpanm/work/1538089417.18351/build.log for details. Retry with --force to force install it.
.....

The --force installation has installed Analizo but failed on Building and testing. However i have checked that I can get source code metrics which i needed most. Is there anything that I need to do?

I hope in future, you are going to make the process much easier for ubuntu user. Finally thank you in advance for your help and support.
