### ISSUE TITLE
Analizo includes dependencies (i.e., graph nodes) to external dependencies

### ISSUE THREAD

**Issue by joenio** [analizo/analizo#151]
hi @gerardorosiles, copying point 1. from issue #146 to here in order to separate discussion by topics.

```
We have been doing tests in our app with the following source code package:
https://github.com/imageprocessor/cv4j

We are using analizo graph --modules to analyze dependencies. We are seeing
the following unexpected analizo behaviors in the DOT file.

Analizo includes dependencies (i.e., graph nodes) to external Java dependencies.
For instance on cv4j we get:
java.io.Serializable
java.util.concurrent.ThreadFactory
RecycleView
Comparable
RuntimeException
```

**Comment by joenio** [comment]
I'm not sure if I understand the real problem here, Analizo should not includes external dependencies on graph? Why?

**Comment by gerardorosiles** [comment]
Hi Joenio, Sorry I did not explay myself well. Analizo is including external dependencies as nodes in the graph. A very common one we see in java projects is java.io.someClass; they appears as  nodes.

**Comment by joenio** [comment]
I run `analizo graph` on `cv4j` and the issue seens to be solved, analizo doesn't list external nodes as `java.util.Serializable` anymore, I'm attaching the `analizo graph` and `doxyparse` output in order to keep tracking. [cv4j.zip](https://github.com/analizo/analizo/files/4262481/cv4j.zip)
