### ISSUE TITLE
Message: "Not a HASH reference at /Library/Perl/5.18/Analizo/Extractor/Doxyparse.pm line 54."

### ISSUE THREAD

**Issue by christinaflach** [analizo/analizo#155]
Project Apache HTTP Server 2.4.38 (httpd): 2.4.38 is the latest available version.
http://httpd.apache.org/download.cgi

$analizo metrics ./httpd-2.4.38/ --language c -I ./httpd-2.4.38/include/ 
returns:
"Not a HASH reference at /Library/Perl/5.18/Analizo/Extractor/Doxyparse.pm line 54."

The problem happens while parsing the file 
./httpd-2.4.38/modules/generators/mod_suexec.h

**Comment by joenio** [comment]
http-2.4.38 source-code download link: http://archive.apache.org/dist/httpd/httpd-2.4.38.tar.bz2
