### ISSUE TITLE
.Json instead of .yml 

### ISSUE THREAD

**Issue by Ramith-Indula** [analizo/analizo#158]
Hi, 
any particular way that I can get the metrics output as a .json instead of .yml ?

**Comment by joenio** [comment]
you can use some tool to converts YAML to JSON, but Analizo has no way to do that by default, and there is no plan to add this on the analizo side for now.

I found a yaml2json tool at https://github.com/solderjs/yaml2json you can try it

Also, I did some experiments here to convert YAML to JSON in Perl, and I did a small script to to the job, see: https://github.com/joenio/yaml2json
