### ISSUE TITLE
Can't install Analizo on Debian using apt install analizo command

### ISSUE THREAD

**Issue by gerardorosiles** [analizo/analizo#172]
I am trying to install Analizo 1.24 following instructions on : 

 https://github.com/analizo/analizo/blob/master/INSTALL.md

I just run on the bash shell of a debian:stretch Docker container and then run this command 

apt install analizo

I get this output:

Building dependency tree       
Reading state information... Done
E: Unable to locate package analizo

**Comment by gerardorosiles** [comment]
I was able to install on a running debian:stretch container as follows:

Step 1. Start a debian:stretch container in bash mode

  sudo docker run -it  --rm debian:stretch  bash

Step 2. Once in the container shell, update and install needed packages

  apt-get update
  apt-get -y install sudo apt-utils vim wget

Step 3. Add the file analizo.list

  vim /etc/apt/sources.list.d/analizo.list

with the following contents

  deb http://analizo.org/download/ ./
  deb-src http://analizo.org/download/ ./

Step 4. Run another updat
  apt-get update

Step 5. Add the signing key for Analizo

  wget -O - http://analizo.org/download/signing-key.asc | apt-key add -

Step 6. Install Analizo

  apt install analizo

Step 7: Test analizo

  analizo --help
  analizo --version

**Comment by gerardorosiles** [comment]
However the version installed is version 1.23.0 (as this is what is sitting on the analizo.org website :)  ) : 

root@ed4d9d91cc9c:/# analizo --version
analizo version 1.23.0

**Comment by joenio** [comment]
@gerardorosiles thanks for your feedback here. Yes in fact I didn't release a package for Analizo 1.24.0, sorry for that, I'm on transition to add Analizo as an oficial Debian package, I hope Analizo 1.25.0 will be available on Debian repositories soon.

**Comment by joenio** [comment]
Steps:
- [ ] Release Analizo to CPAN
- [ ] Update analizo debian package
  * https://salsa.debian.org/perl-team/modules/packages/analizo/-/blob/master/debian/changelog
- [ ] Wait for a new Doxygen release including the fix for #173 
  * Update debian package for doxygen (it includes doxyparse)
- [ ] Declare on analizo dependencies the new doxyparse debian package
- [ ] Upload analizo on debian and make sure it will be uploaded to oficial repositories

**Comment by gerardorosiles** [comment]
@joenio , Thanks for the update.
