### ISSUE TITLE
should propagate failure in extractor

### ISSUE THREAD

**Issue by paulormm** [analizo/analizo#3]
when the extractor (e.g. doxyparse) fails, analizo just reports nothing. It should exit with a failure code explicitly.

**Comment by joenio** [comment]
@paulormm the links for mezuro mailing list is returning "404 Not Found", do we have some backup of the mailing list archives?

**Comment by paulormm** [comment]
ASL (a Brazilian Free Software Association) lost all mailing lists at listas.softwarelivre.org in the past. We don't have a complete backup but I've a lot of email from this Mezuro mailing list. I'll send to you these cited threads.

**Comment by joenio** [comment]
thanks @paulormm.

This issue was solved on newest analizo versions. Now, analizo reports error raised on doxyparse, see an example where doxyparse fails (this bug already reported on #120).

```console
joenio@linda-lee:~/src/analizo-projects/analizo (master)$ ./bin/analizo metrics ../testes/mlpack/
terminate called after throwing an instance of 'std::logic_error'
  what():  basic_string::_M_construct null not valid
Aborted
doxyparse error at /home/joenio/src/analizo-projects/analizo/lib/Analizo/Extractor/Doxyparse.pm line 178.
```
