### ISSUE TITLE
Functions are listed twice in C code

### ISSUE THREAD

**Issue by runys** [analizo/analizo#38]
The doxyparse output for the test case in number 2 is the following:

$ doxyparse .
file /home/terceiro/src/analizo/analizo/t/samples/multidir/c/lib/lib.h
module lib.h
   
file /home/terceiro/src/analizo/analizo/t/samples/multidir/c/lib/main.c
module lib/main.c
   
file /home/terceiro/src/analizo/analizo/t/samples/multidir/c/src/main.c
module src/main.c
   function main(int,char **) in line 3
      protection public
      4 lines of code
      2 parameters
      1 conditional paths
      uses function say_hello() defined in lib.h

When the file is declared in XXX.h and implemented in XXX.c (which should always be the case with sane code), this it not harmfull, only slows things a bit since every single function is processed twice. But in cases such as the above, this bug actually causes wrong information to be produced.
In the above case lib/lib.h and lib/main.c should actually be considered a single module.

As seen at:
http://analizo.org/Development/ActionItem13

References:
test case number 2: http://analizo.org/Development/ActionItem2

**Comment by joenio** [comment]
I see no any good solution for this issue.
