### ISSUE TITLE
Complete CLang C/C++ parser

### ISSUE THREAD

**Issue by paulormm** [analizo/analizo#43]
CLang parser/extractor
  see https://gitorious.org/analizo/analizo/commits/clang-extractor

**Comment by joenio** [comment]
the clang should be removed from analizo...

**Comment by joenio** [comment]
related commits 0278c09cf6311b58f9f585a7f2eb0f2bdcf1a0b2 4747266490deb21e44313dd6c6c70cc3c8ac498a 18338ca3c3b7249b6c268cd503113192a62ac18d 5200dac3acd0cdb8a7d5e5cf15210f0ab8c1aa51 a849103581616c095e34024618abfab0a2fc0dc4
