### ISSUE TITLE
GItorious down

### ISSUE THREAD

**Issue by diraol** [analizo/analizo#73]
Folks, gitorious is going down.

You probably know that. So it would be nice to review any references to gitorious on all repo files and change it to the new URLs, like on:

https://github.com/analizo/analizo/blob/master/HACKING.md

Cheers!

**Comment by paulormm** [comment]
I've fixed Analizo repo URL and also migrated doxyparse repo GitLab.

@terceiro  and @joenio:  Can I migrate all repo related to Analizo project to GitLab? Now, we've a group there - https://gitlab.com/groups/analizo.

**Comment by terceiro** [comment]
fine by me

**Comment by joenio** [comment]
I think we should stay here in github.
