### ISSUE TITLE
No metric results with newer doxyparse version

### ISSUE THREAD

**Issue by rafamanzo** [analizo/analizo#78]
Running analizo with newer doxyparse version does not produce any metrics failling silently

```bash
`--> analizo metrics .
sh: doxyparse: command not found
---
change_cost: ~
total_abstract_classes: 0
total_cof: 1
total_eloc: 4781
total_loc: 0
total_methods_per_abstract_class: 0
total_modules: 0
total_modules_with_defined_attributes: 0
total_modules_with_defined_methods: 0
```

This is related to https://github.com/analizo/analizo/issues/77

**Comment by terceiro** [comment]
> sh: doxyparse: command not found

is `doxyparse` in your $PATH?

**Comment by rafamanzo** [comment]
It was my fault while compiling it.

Now it requires a compilation optin in order to get doxyparse extension compiled: `cmake -Dbuild_parser=ON .`. Otherwise no doxyparse binary is generated.

I'll test soon with this new version, but looks like this solves. Sorry.
